### ISSUE TITLE
염주섭 필요한 기능들입니다

### ISSUE THREAD

**Issue by yeombear** [CodersHigh/ITCTCatalog2015#23]
1. ImageScroll에서 줌인하고, 어느정도 줌인되면 페이지가 넘어가는 것
2. 메뉴버튼을 누르면 하단에서 메뉴바가 등장하는 것
3. swift로 특정 image(헬기와 같은)의 좌표값을 float 변수에 저장하고, (x,y)
   이 변수로 Text를 변경하는 것
4. 애니메이션이 진행되는 동안, 계속해서 변하는 두점을 연결하는 선 그리는 swift코드?
5. ImageScroll 상단에 여러개의 container띄우기
6. 텍스트 공유하기, 이미지 공유하기 창 하단에서 modal Up 되는 것

혹시 필요하시면 제 메일은 yeombear@gmail.com입니다.

**Comment by lingostar** [comment]
1. ImageScroll에서 Zoom In & out 하는 것은 PilotPlant를 1.13 버전으로 업데이트 한 뒤, PilotPlantCatalog를 참조.
2. 별도의 이슈 생성 바람.
3. 추가 설명 필요
4. 추가 설명 필요
5. 현재 기능을 응용해서 처리 가능
6. 별도의 이슈 생성 바람.
