### ISSUE TITLE
메뉴버튼을 누르면 하단에서 메뉴바가 등장하는 것

### ISSUE THREAD

**Issue by yeombear** [CodersHigh/ITCTCatalog2015#24]
현재 저는 지도 앱이기 때문에 화면의 상당 부분을 지도로 할당하고 있습니다.
8개의 메뉴를 갖고 있는 앱이라, 이를 화면에 항시 표시할 수 없는 상태입니다.

그래서 화면 하단 메뉴버튼을 숨겨뒀다가  화면 우측 하단에 ^ 의 버튼을 누르면
메뉴바가 일종의 모달처럼 아래에서 올라오게 하고 싶습니다.

**Comment by lingostar** [comment]
일단 애니메이션 없는 뷰의 전환으로 구현합니다.

만약 애니메이션을 하고 싶으면 다음 중 한 가지 방법을 권합니다.
1번부터 어렵지만 좋은 구현입니다.
1. UIView Animation을 이용해 조각 뷰 이동 구현.
2. PilotPlant의 PopOver 참고해서 팝오버로 처리
