### ISSUE TITLE
텍스트 공유하기, 이미지 공유하기

### ISSUE THREAD

**Issue by yeombear** [CodersHigh/ITCTCatalog2015#25]
특정 텍스트 문구(예를 들어 웹페이지 주소 등)을 
외부 앱으로 share하는 기능을 추가하고 싶습니다.

현재 각종 앱에서 텍스트 문구에서 공유하기를 누르면
하단에서 앱 목록 혹은 air Drop 이 등장하면서 공유할 수 있는 창이 등장합니다.

이를 텍스트 공유하기와 이미지 공유하기로 표현하고 싶습니다.

**Comment by lingostar** [comment]
PilotPlantCatalog의 Activity를 참고하세요.

Activity에 본인의 커스텀 아이콘을 삽입하고 싶다면 이슈를 만드세요,

이미 만들어둔 게 있으니 PilotPlant를 업데이트 하겠습니다.
