### ISSUE TITLE
필요한 기능들 보충 설명입니다.

### ISSUE THREAD

**Issue by yeombear** [CodersHigh/ITCTCatalog2015#26]
1. 수업시간에 다뤘듯 애니메이션으로 특정 이미지를 시간에 따라 이동시킬 수 있었습니다.
   이때 이동하는 이미지의 위치 pixel값을 특정 변수인 x와 y로 가져오고,
   이 x,y값을 화면상의 text로 출력하고 싶습니다.
   pilotplant가 아니더라도 함수 코드라도 알려주시면 할 수 있을 것 같습니다.
2. 2개의 애니메이션이 진행되어서 2개의 이미지가 각기 움직이고 있을 때,
   이 두 이미지를 연결하는 선을 그리고 싶습니다.

이것도 swift코딩으로 해결해야할 문제 같은데, 설명 부탁드립니다ㅠㅠ

**Comment by lingostar** [comment]
이 부분은 수업시간에 했던 프로젝트를 드리겠습니다.
추가적인 질문 있으면 전화로 문의하세요.

[Animations.zip](https://github.com/CodersHigh/ITCTCatalog2015/files/61268/Animations.zip)
