### ISSUE TITLE
구현하고 싶은 기능 설명입니다.

### ISSUE THREAD

**Issue by shhan826** [CodersHigh/ITCTCatalog2015#27]
1. 이미지를 넣고 스크롤 할 수 있게 하는 기능을 구현하고 싶습니다. (좌우)
2. 텍스트를 입력, 여러 선택하는 옵션중에 선택하는 것, 날짜 선택하는 창, 체크박스를 구현하고 싶습니다.
3. 제한된 구역 안에서 슬라이드를 하면 좌우에 숨겨져 있던 다른 이미지를 볼 수 있게 하는 기능을 구현하고 싶습니다.

**Comment by lingostar** [comment]
1. PilotPlant의 Photo Carousel을 참고하세요.
2. 1. 

모두 확인 된 이슈인 걸로 알고 있습니다. 
안되는 부분 개별 티켓으로 만들어 주세요.
