### ISSUE TITLE
Navigation bar item 접근 질문입니다

### ISSUE THREAD

**Issue by snowcat-Jung** [CodersHigh/ITCTCatalog2015#28]
View Controller1에서 navigation bar통해 VC2(back) - VC3(back) 이런 구조에서

 VC3 에서 back button 누르면 pilot plant의 back to root vc 나 
VC2 안에 문장을 심어서 VC1으로 돌아가게 수정하려고 합니다. 

VC3 back button 설정을 바꾸려면 어떤 문서에서 수정을 해야 하나요? 찾을 수가 없어서... VC3는 스토리보드 상에서 안보이고(네비게이션바 형태만 나타나고) 시뮬레이터에서는 나타나는데 어디서 바꿔야 하는지요...

**Comment by lingostar** [comment]
첨부한 프로젝트를 참고하세요.

[TestPP.zip](https://github.com/CodersHigh/ITCTCatalog2015/files/61260/TestPP.zip)
