### ISSUE TITLE
ActionSheet

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/ITCTCatalog2015#33]
#31 Merge 관련

0:04초 부근

 ActionSheet가 올라오는 화면에도 이전 화면이 배경으로 있어야 할 듯 합니다. ContainerView를 활용하세요

**Comment by lingostar** [comment]
1:24 초 부근의 얼러트도 마찬가지입니다.

**Comment by shhan826** [comment]
시도해보았지만, Modal Dismiss를 사용할 때 내려가는 애니메이션이 말씀하신대로 고치니까 더 어색하게 만드는 것 같습니다. 혹시 이 애니메이션을 없앨 수 있는 방법이 있을까요?

**Comment by lingostar** [comment]
ActionSheet를 사용한게 아니라 모달을 올린건가요?
그냥 ActionSheet이면 될 것 같은데요?

원격지원이 필요하면 팀 뷰어 설치하고 #39 에 있는 제 전화번호로 연락주세요.

**Comment by shhan826** [comment]
Alert를 보여주고 뒤로 돌아갈 때 Segue를 사용해서 돌아가게 되면 탭바와 네비게이션바가 날라간 채로 이동하게 됩니다;;
