### ISSUE TITLE
PickerView 문제

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/ITCTCatalog2015#34]
#31 Merge 관련

0:20초 부근

Picker만 덩그러니 있는 화면을 실제 앱으로 만들지는 않겠죠?
테이블 뷰 셀 내부 또는 뷰 컨트롤러 구성을 통해 이전 장면과의 연속성을 만들어 주세요.
ContainerView를 활용하세요

**Comment by lingostar** [comment]
0:28 초 부근도 마찬가지입니다.

**Comment by shhan826** [comment]
아 이거 맨 처음에 이렇게 하려고 했다가 에러가 나서 바꾼겁니다. 콘테이너에 넣기만 하면 설정한 피커가 안뜨고 텅 빈 상태로 나옵니다... ㅠㅠ
