### ISSUE TITLE
만들기 - 요일 선택의 디테일

### ISSUE THREAD

**Issue by lingostar** [CodersHigh/ITCTCatalog2015#35]
#31 Merge 관련

0:51초 부근

1회 분량은 요일 선택에 따라 달라져야 하는 것 같네요.
화/목을 순차적으로 선택함에 따라 업데이트 되는 1회 분량을 보여주면 보다 사실적일 듯 합니다.

**Comment by shhan826** [comment]
업데이트를 하는 모습을 보여주기 위해서는 제 능력선에선 show segue를 사용해야 할 것 같은데요, 스크롤이 아래로 내려진 상태에서 바꾸는 것이라 버튼을 클릭하면 다시 맨 위로 올라가서 화면이 뜨게 됩니다. ㅠㅠㅠ
