### ISSUE TITLE
PilotPlant 올린 후 돌리면 다음과 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by sociengineer** [CodersHigh/ITCTCatalog2015#36]
![2015-12-16 2 38 57](https://cloud.githubusercontent.com/assets/7139730/11833154/2f07dee8-a403-11e5-92f2-5376fc96b5de.png)
파일럿 플랜트를 copy로 추가하고, Embeded Binary에서도 넣고,  Build setting의 search path중 Framework search paths에 제 프로젝트 명 아래 경로에 Common/Simulator 안에 PilotPlant를 넣고 돌려주면 다음과 같은 에러가 발생하여 처음에 시뮬레이터 화면이 돌다가 앱이 켜지면 하얀화면이 나오고 다음과 같은 에러가 나옵니다.

**Comment by lingostar** [comment]
저 에러는 알려진 이슈이며, swift 에러입니다. 대응 방안이 있지만 조금 불편하기도 합니다.
일단 아래 라이브러리를 사용해 보고 안되면 원격 접속을 사용하죠.
[PilotPlant.framework.zip](https://github.com/CodersHigh/ITCTCatalog2015/files/63609/PilotPlant.framework.zip)

**Comment by sociengineer** [comment]
보내주신 파일 받아서 돌리니까 잘됩니다~ 감사합니다.
