### ISSUE TITLE
프로그레스 바의 height를 바꾸려면 어떻게 해야하나요?

### ISSUE THREAD

**Issue by sociengineer** [CodersHigh/ITCTCatalog2015#37]
Progressive bar의 높이를 조정해서 두껍게 나오게 하고 싶습니다.  default height가 2로 설정되어 바꿀 수 없게 되어 있는데 이것을 바꿀 수 있는 방법은 무엇인가요?

**Comment by lingostar** [comment]
오토레이아웃으로 높이를 주면 됩니다.

**Comment by sociengineer** [comment]
감사합니다. 해결되었습니다~
