### ISSUE TITLE
AudioScene에 음악을 넣어도 재생되지 않습니다.

### ISSUE THREAD

**Issue by sociengineer** [CodersHigh/ITCTCatalog2015#39]
![2015-12-16 6 32 56](https://cloud.githubusercontent.com/assets/7139730/11837337/82b89f4e-a423-11e5-8c68-627c6461d51f.png)
아래와 같은 에러가 뜨면서 노래가 재생되지 않습니다.

**Comment by lingostar** [comment]
audioFileName의 N자는 대문자인가요?

**Comment by sociengineer** [comment]
![2015-12-16 8 24 41](https://cloud.githubusercontent.com/assets/7139730/11839714/4e97d4a4-a433-11e5-993b-40802840e68b.png)
![2015-12-16 8 25 39](https://cloud.githubusercontent.com/assets/7139730/11839715/4e9df12c-a433-11e5-980f-b8d2d7e92947.png)
넵 audioFileName은 N이 대문자로 되어 있는 것 같습니다~

**Comment by lingostar** [comment]
아뇨, 저기 말고 스토리보드 뷰 컨트롤러의 변수를 확인해 주세요.

**Comment by sociengineer** [comment]
![2015-12-16 8 49 35](https://cloud.githubusercontent.com/assets/7139730/11840120/912f526c-a436-11e5-995f-4d0853d52cef.png)
이곳을 말씀하신 것이 맞나요?

**Comment by lingostar** [comment]
음.. 확장자 aiff의 대소문자를 PilotPlantCatalog에 있는 것 처람 맞춰볼래요?

**Comment by sociengineer** [comment]
![2015-12-16 9 20 12](https://cloud.githubusercontent.com/assets/7139730/11840659/de0e2302-a43a-11e5-8e86-4b2fbb618b78.png)
![2015-12-16 9 20 32](https://cloud.githubusercontent.com/assets/7139730/11840658/de0a2b94-a43a-11e5-832c-4b23255b76b9.png)
교수님 확장자 aiff는 다 소문자로 되어 있는데 어떻게 대소문자로 맞추라는 것인지 모르겠습니다~

**Comment by lingostar** [comment]
공일영-5546-74둘둘 로 문자주세요

**Comment by sociengineer** [comment]
선생님께서 원격으로 해결해 주셨습니다. 앱을 삭제했다가 다시 깔고, 뭘 바꾸셨는데 기억이 안나서 설명을 못쓰겠어요ㅠ
