### ISSUE TITLE
테이블셀의 구분 간격이 없습니다.

### ISSUE THREAD

**Issue by sociengineer** [CodersHigh/ITCTCatalog2015#40]
![2015-12-16 6 38 57](https://cloud.githubusercontent.com/assets/7139730/11837461/55878d90-a424-11e5-8c34-10d20cbd7256.png)
스토리보드에서는 테이블 셀 사이의 구분선이 있는데, 시뮬레이션 화면에서는 안보입니다. 시뮬레이션 화면에서도 보이게 하려면 어떻게 해야하나요?

**Comment by lingostar** [comment]
실제로 시뮬레이터에서 보이는 건데, 시뮬레이터 스크린 사이즈를 축소해서 보였다가 안 보였다가 하는 거예요.
시뮬레이터 축소 비율을 줄이면 할 수 있어요.

**Comment by sociengineer** [comment]
100%로 보니까 선이 보입니다~ 감사합니다.
