### ISSUE TITLE
Navigation View Controller 하나 더 질문드려요

### ISSUE THREAD

**Issue by snowcat-Jung** [CodersHigh/ITCTCatalog2015#41]
VC1- VC2-VC3 에 추가로 -VC4 해서 4에서 2로 가는건 어떻게 하나요??? 코드 막 수정해서 됐던거 같은데 단 컴퓨터 xcode 에서 하니까 안되네요

**Comment by lingostar** [comment]
음.... 그건 제가 안 만들어뒀네요.

**Comment by lingostar** [comment]
그리고 코드로 하지 않으면 좀 어려울 것 같기도 해요.
PilotPlant에 액션을 넣어면서 매개변수를 넘기는 게 좀 곤란하군요.
